# Generated by Django 4.2.15 on 2024-09-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='ID Telegram')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя канала')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser', verbose_name='Пользователь бота')),
            ],
            options={
                'verbose_name': 'Телеграм канал',
                'verbose_name_plural': 'Телеграм каналы',
            },
        ),
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='ID Telegram')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('subscribed', models.BooleanField(default=False, verbose_name='Подписан')),
                ('datetime_subscribe', models.DateTimeField(blank=True, null=True, verbose_name='Время подписки')),
                ('datetime_unsubscribe', models.DateTimeField(blank=True, null=True, verbose_name='Время отписки')),
                ('invite_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramchat', verbose_name='Пригласительная ссылка')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creates_join_request', models.BooleanField(default=False, verbose_name='Запрос на добавление')),
                ('creator', models.CharField(blank=True, max_length=250, null=True, verbose_name='Создатель')),
                ('expire_date', models.CharField(blank=True, max_length=150, null=True, verbose_name='expire_date')),
                ('link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка')),
                ('is_primary', models.BooleanField(blank=True, null=True, verbose_name='Is_primary')),
                ('is_revoked', models.BooleanField(blank=True, null=True, verbose_name='Is revoked')),
                ('member_limit', models.IntegerField(blank=True, null=True, verbose_name='Лимит подписок')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='имя')),
                ('pending_join_request_count', models.IntegerField(blank=True, null=True, verbose_name='pending_join_request_count')),
                ('telegram_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramchat', verbose_name='Телеграм канал')),
            ],
            options={
                'verbose_name': 'Пригласительная ссылка',
                'verbose_name_plural': 'Пригласительные ссылки',
            },
        ),
    ]
