# Generated by Django 4.2.15 on 2024-09-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramchat',
            name='bot_user',
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='chat_id',
            field=models.BigIntegerField(default=-1, verbose_name='ID Канала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Username канала'),
        ),
    ]
