# Generated by Django 4.2.15 on 2024-09-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_telegramchat_bot_user_telegramchat_chat_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramchat',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='invitelink',
            name='public_link',
            field=models.BooleanField(default=False, verbose_name='Публичная ссылка'),
        ),
    ]
