# Generated by Django 4.2.15 on 2024-09-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_rename_user_name_telegramchat_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitelink',
            name='creator',
        ),
        migrations.AddField(
            model_name='invitelink',
            name='creator_full_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Создатель Имя'),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='creator_telegram_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Создатель id'),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='creator_username',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Создатель username'),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='notification',
            field=models.BooleanField(default=False, verbose_name='Уведомление о подписчиках'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название'),
        ),
    ]
