# Generated by Django 4.2.15 on 2024-09-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_invitelink_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsubscriber',
            name='telegram_chat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bot.telegramchat', verbose_name='Телеграм канал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramsubscriber',
            name='invite_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.invitelink', verbose_name='Пригласительная ссылка'),
        ),
        migrations.AlterField(
            model_name='telegramsubscriber',
            name='telegram_id',
            field=models.PositiveBigIntegerField(verbose_name='ID Telegram'),
        ),
        migrations.AddConstraint(
            model_name='telegramsubscriber',
            constraint=models.UniqueConstraint(fields=('telegram_chat', 'telegram_id'), name='unique_telegram_chat_and_tg_user_id'),
        ),
    ]
